# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65a7491a91404dbf9b63faf1ff5192de37629310f29d7c0428dc5e8fdc49e90c7d57b3bdcf2d889f33a51167742a2f5db47cb2318c200d965344ce5392b04936

test:
  secret_key_base: 1aed47ca68f9c5929a34f92734b1da7f96c79e23242efd62c3c31c16e28e1204945a8189a28de25293752f668c038cb7f391006f7815f0204b97d7053e336ed2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
